### ISSUE TITLE
sugerencia

### ISSUE THREAD

**Issue by DiegoKoz** [pablotis/capacidad_instalada_indec#1]
Hola!

vengo a molestar para decir que podrías hacer algo como lo siguiente 

`
tema <-        caption = "Fuente: Elaboración propia en base al INDEC.") + 
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 1,
                                  vjust = 10,
                                  family = "American Typewriter",
                                  face = "bold",
                                  size = 14,
                                  lineheight = 1),
        plot.subtitle = element_text(hjust = 1,
                                     vjust = 5,
                                     family = "American Typewriter",
                                     face="italic"),
        plot.caption = element_text(hjust = 1,
                                    vjust = -6,
                                    family = "American Typewriter",
                                    face="plain"),
        axis.text = element_text(family = "American Typewriter",
                                 face="bold"), 
plot.margin = unit(c(2.5,1,1,1), "cm"))
`

y después en los gráficos solo agregar un 

`
plot_slopegraph(df) + 
 tema

`

así queda un código mucho más compacto y cómo de leer :+1:

**Comment by pablotis** [comment]
Hecho! Mil gracias por la sugerencia \m/
